config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "pages#home"

  resources :users do
    resources :bookings
    resources :reviews
    resources :guitars
    resources :favourites, only: [:index]
  end

  resources :guitars do
    resources :bookings
    resources :reviews
    resources :favourites, only: [:create, :destroy]
    resources :chatrooms do
      resources :messages, only: [:index, :create]
    end

    collection do
      get 'owned'
    end


  end


  resources :bookings, only: :destroy
  resources :reviews, only: :destroy
  resources :guitars, only: :destroy
  resources :chatrooms, only: :index

end

app/models/guitar.rb
class Guitar < ApplicationRecord
  include ActionView::Helpers

  belongs_to :user
  has_many :users, through: :favourites
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :favourites, dependent: :destroy
  has_many_attached :photos, dependent: :destroy

  has_many :chatrooms, dependent: :destroy

# Published Guitars Search
  include PgSearch::Model
  pg_search_scope :search_published_guitars,
    against: [ :name, :caption, :description, :guitar_type ],
    using: {
      tsearch: { prefix: true }
    },
    associated_against: {
      user: [:name, :username]
    },
    :conditions => lambda { |guitar| { published: true } }

  # Favourites Search
  include PgSearch::Model
  pg_search_scope :search_user_favourites,
    against: [:name, :caption, :description, :guitar_type],
    associated_against: {
      favourites: [:user_id]
    },
    using: {
      tsearch: { prefix: true }
    }

  def average_rating
    reviews.length == 0 ? "" : "#{content_tag(:i, "", class: "bi bi-star")} #{reviews.average(:rating).round(1)}".html_safe
  end

end

app/controllers/guitars_controller.rb
class GuitarsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_guitar, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:index, :new, :edit, :owned]

  def destroy
    @guitar = Guitar.find(params[:id])
    if @guitar.destroy!
      puts "trying to destory!"
      redirect_to guitars_path
    else
      redirect_to guitars_path
    end
  end

  def index
    @users = User.joins(:guitars).where(guitars: { published: true }).distinct
    if params[:query].present?
      @guitars = Guitar.search_published_guitars(params[:query])
      @markers = @users.geocoded.map do |user|
        guitar = user.guitars.where(id: @guitars.pluck(:id)).first
        marker_guitar_photo = guitar&.photos&.first
        {
          lat: user.latitude,
          lng: user.longitude,
          info_window_html: render_to_string(partial: "infos_window", locals: {user: user}),
          marker_html: render_to_string(partial: "marker")
        }
      end
    else
      @guitars = Guitar.where(published: true)
      # DRY - refactor this code
      @markers = @users.geocoded.map do |user|
        {
          lat: user.latitude,
          lng: user.longitude,
          info_window_html: render_to_string(partial: "infos_window", locals: {user: user}),
          marker_html: render_to_string(partial: "marker")
        }
      end
    end
  end

  def new
    @guitar = Guitar.new
    @booking = @guitar.bookings.build
  end


  def create
    @guitar = Guitar.new(guitar_params)
    @guitar.user = current_user
    if @guitar.save
      redirect_to @guitar
    else
      render :new
    end
  end

  def show
    @user = @guitar.user
    @booking = @guitar.bookings.build
    @more_guitars = @user.guitars.where.not(id: @guitar.id)
    @reviewable = @guitar.bookings.where("start_date" < Date.today.to_s).where(user: current_user)
    @markers =
      [
        lat: @user.latitude,
        lng: @user.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {guitar: @guitar}),
        marker_html: render_to_string(partial: "marker")
      ]
    @favourite = current_user.favourites.find_by(guitar_id: @guitar)
  end

  def edit
  end

  def update
    @guitar.user = current_user
    if @guitar.update(guitar_params)
      redirect_to @guitar
    else
      render :edit
    end
  end

  def owned
    @guitars = current_user.guitars
    @active_guitars = current_user.guitars.where(published:true)
    @inactive_guitars = current_user.guitars.where(published:false)
  end

  private

  def guitar_params
    params.require(:guitar).permit(:name, :address, :caption, :description, :cost_per_day, :guitar_type, :user_id, photos: [])
  end

  def set_guitar
    @guitar = Guitar.find(params[:id])
  end

  def set_user
    @user = current_user
  end
end

app/views/guitars/_form.html.erb
<%= f.input :address,
  input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
  wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
%>

app/views/guitars/_gallery_modal.html.erb
<div class="gallery-modal">
  <div class="gallery">

    <div class="d-flex justify-content-between">
      <p data-action="click->modal#closeGallery">close</p>
    </div>

    <div class="d-flex flex-column justify-content-center">
      <%= cl_image_tag @guitar.photos[0].key %>
      <%= cl_image_tag @guitar.photos[1].key %>
      <%= cl_image_tag @guitar.photos[2].key %>
    </div>

  </div>
</div>

app/views/guitars/_guitars.html.erb
<div class="row mt-3">
  <% guitars.each do |guitar| %>
    <%= link_to guitar_path(guitar), class: "col-md-4 col-sm-6 col-12" do %>

      <div class="g-card selected">
        <div class="g-card-image">
          <% if guitar.photos.attached? %>
            <%= cl_image_tag guitar.photos.first.key, loading: "lazy" %>
          <% else %>
            <p>no img available</p>
          <% end %>
        </div>
        <div class="g-txtbox">
          <h6 class="g-card-name"><%= truncate(guitar.name, length: 27, seperator: ' ') %></h6>
          <p class="g-card-rating"><%= guitar.average_rating %></p>
          <p class="g-card-type"><%= guitar.guitar_type %></p>
          <p class="g-card-price">£<%= guitar.cost_per_day %> per night</p>
          <% if guitar.user == current_user %>
            <p class="g-card-delete">
              <i class="bi bi-trash"></i>
            </p>
          <% end %>
        </div>
      </div>

    <% end %>
  <% end %>
</div>

app/views/guitars/_info_window.html.erb
<% if @guitar.present? %>
  <%= @guitar.name %>
<% else %>
  <%= @booking.guitar.name %>
<% end %>

app/views/guitars/_infos_window.html.erb
<div class="container">
  <%= user.first_name %>
  <ul>
  <% user.guitars.each do |guitar| %>
    <li><%= link_to guitar.name, guitar_path(guitar) %></li>
  <% end %>
  </ul>
</div>

app/views/guitars/_list.html.erb
<div data-refresh-list-target="list">

</div>

app/views/guitars/_marker.html.erb
<% if @guitars.present? %>
  <%= image_tag "guitar.png", height: 30, width: 30, alt: "Logo" %>
<% else %>
  <%= cl_image_tag @guitar.photos[0].key, height: 30, width: 30, alt: "Logo" %>
<% end %>

app/views/guitars/edit.html.erb
<div class="container mt-3">
  <h1>Edit Guitar</h1>
   <%= simple_form_for @guitar do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :caption %>
    <%= f.input :description %>
    <%= f.input :cost_per_day %>
    <%= f.input :guitar_type %>
    <% if @guitar.photos.empty? %>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <% end %>
    <%= f.submit %>
  <% end %>
</div>
<br>

app/views/guitars/index.html.erb
<div id="guitars" class="container mt-4">
  <div class="row">

    <div class="d-flex justify-content-between">
      <h1>GUITARS</h1>
      <% if user_signed_in? %>
        <p><%= link_to "Add Guitar", new_guitar_path, class: "btn btn-secondary" %></p>
      <% end %>
    </div>

    <div class="search-container">
      <%= form_with url: guitars_path, method: :get, class: "d-flex mb-3" do %>
        <%= text_field_tag :query,
          params[:query],
          id: "search",
          class: "form-control",
          placeholder: "Search..."
        %>
        <%= submit_tag "Search", class: "btn btn-dark" %>
      <% end %>
    </div>
  </div>

  <%= render 'guitars/guitars', guitars: @guitars %>

</div>
<%# MAP %>
<div class="container">
  <div class = "col-sm" style="width: 100%; height: 450px; border: 5px solid black"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/guitars/new.html.erb
<div class="container mt-4 mb-5" style="position:relative">
  <h1 class="mb-3">New Guitar</h1>
  <%= simple_form_for @guitar do |f| %>
    <%= f.input :name, label: false, placeholder: "Name" %>
    <%= f.input :caption, label: false, placeholder: "Caption" %>
    <%= f.input :description, label: false, placeholder: "Description" %>
    <%= f.input :cost_per_day, label: false, placeholder: "Cost Per Day" %>
    <%= f.input :guitar_type, label: false, placeholder: "Guitar Type" %>
    <%= f.label :photos, label: "Upload 3 photos", style: "color:#6c757c" %>
    <%= f.input :photos, as: :file, label: false, input_html: { multiple: true, style: "color:#0e000000" } %>
    <%= f.submit class: "btn btn-dark", style: "position:absolute;right:0;margin:0 12px" %>
  <% end %>
</div>
<br>

app/views/guitars/owned.html.erb
<div class="container mt-3" style="min-height: 60vh">
  <h1>My Guitars</h1>
  <% if @guitars.present? %>

    <% if @active_guitars.present? %>
    <h2>My Active Guitars</h2>
      <%= render 'guitars', guitars: @active_guitars %>
    <% end %>

    <% if @inactive_guitars.present? %>
    <h2>Inactive Guitars</h2>
      <%= render 'guitars', guitars: @inactive_guitars %>
    <% end %>

  <% else %>
    <div class="no-content">
      <p>You haven't added any guitars</p>
      <%= link_to "Add a Guitar", new_guitar_path %>
    </div>
  <% end %>
</div>

app/views/guitars/show.html.erb
<div class="container mt-3 mb-2  d-flex align-items-center justify-content-between">
  <div class="d-flex justify-content-between guitar-name">
    <h1><%= @guitar.name %></h1>
    <div class="d-flex align-items-center">
      <% if @guitar.user != current_user %>
        <% if @favourite %>
          <%= button_to guitar_favourite_path(@guitar, @favourite), method: :delete, class: "fav-btn" do %>
            <i class="bi bi-heart-fill"></i>
          <% end %>
        <% else %>
          <%= button_to guitar_favourites_path(@guitar), method: :post, class: "fav-btn" do %>
            <i class="bi bi-heart"></i>
          <% end %>
        <% end %>
        <button class="share"><i class="bi bi-share"></i></button>
      <% end %>
    </div>

  </div>

  <div class="d-flex justify-content-center align-items-center">
    <% if @guitar.user == current_user %>
      <%= link_to "Edit", edit_guitar_path(@guitar), class: "btn btn-dark" %>
      <%= simple_form_for(@guitar, authenticity_token: true, method: :delete) do |f| %>
        <%= f.button :submit, "Delete", class: "btn btn-danger" %>
      <% end %>
    <% end %>
  </div>
</div>
<div class="container">
  <div class="img-box" data-controller="modal">
    <div class="img-1" data-action="click->modal#openGallery"><%= cl_image_tag @guitar.photos[0].key %></div>
    <div class="img-2" data-action="click->modal#openGallery"><%= cl_image_tag @guitar.photos[1].key %></div>
    <div class="img-3" data-action="click->modal#openGallery"><%= cl_image_tag @guitar.photos[2].key %></div>
    <%= render "guitars/gallery_modal" %>
  </div>

  <div class="info-box mt-4 mb-3">
    <div class="guitar-info">
      <!-- <p><%= @guitar.caption %></p> -->
      <div class="d-flex justify-content-between">
        <div>
          <h4>Renting from <%= @guitar.user.first_name %></h4>
          <p><%= @guitar.guitar_type %></p>
        </div>
        <%= button_to "Message", guitar_chatrooms_path(guitar_id: @guitar.id), method: :post, class: "btn btn-dark" %>
      </div>
      <hr>
      <p id="description"><%= @guitar.description %></p>
      <!-- <p><%= @user.address %></p> -->
    </div>

    <div class="bookings" data-controller="modal booking">
      <div class="d-flex justify-content-between">
        <p id="cost"><strong>£<%= @guitar.cost_per_day %></strong> day </p>
        <div class="d-flex">
          <p><%= @guitar.average_rating %></p>
          <!-- Will activate modal to show reviews -->
          <p id="reviews" data-action="click->modal#openReview"><%= @guitar.reviews.count %> reviews</p>
        </div>
      </div>

        <%= simple_form_for [@guitar, @booking] do |f| %>
          <div>
            <%= f.input :start_date, html5: true, input_html: {class: "datepicker"}, value: Date.today.to_s, data: { target: "form", action: "change->modal#bookingUpdate" }   %>
            <%= f.input :end_date, html5: true, input_html: {class: "datepicker"}, value: (Date.today + 1).to_s, data: { target: "form", action: "change->modal#bookingUpdate" }  %>
            <%= f.submit 'Book', class: "btn btn-dark" %>
          </div>
        <% end %>
        <div class="container mt-3" data-controller="booking">
          <p id="total-cost">Total: £<%= @guitar.cost_per_day %></p>
        </div>
    <%= render "reviews/review_modal" %>
    </div>
  </div>

  </div>

<div class="container">
  <hr>
  <h5> Pickup location...</h5>
  <%#= @user.address %>
</div>
<br>
<div class = "container col-sm mb-3" style="width: 100%; height: 480px; margin: 0 auto; border: 1px solid lightgrey"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

<% if @more_guitars.present? %>
  <div class="container">
  <hr>
    <h5>More Guitars available from <%= @user.first_name %></h5>
    <%# user image avatar %>
    <br>
    <div class="row">
      <% @more_guitars.limit(3).each do |guitar| %>
        <%= link_to guitar_path(guitar), class: "col-md-4 col-sm-6 col-12" do %>

          <div class="g-card selected">
            <div class="g-card-image">
              <% if guitar.photos.attached? %>
                <%= cl_image_tag guitar.photos.first.key %>
              <% else %>
                <p>no img available</p>
              <% end %>
            </div>
            <div class="g-txtbox">
              <h6 class="g-card-name"><%= truncate(guitar.name, length: 27, seperator: ' ') %></h6>
              <p class="g-card-rating"><%= guitar.average_rating %></p>
              <p class="g-card-type"><%= guitar.guitar_type %></p>
              <p class="g-card-price">£<%= guitar.cost_per_day %>0 per night</p>
            </div>
          </div>

        <% end %>
      <% end %>

    </div>
  </div>
<% end %>