config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "pages#home"

  resources :users do
    resources :bookings
    resources :reviews
    resources :guitars
    resources :favourites, only: [:index]
  end

  resources :guitars do
    resources :bookings
    resources :reviews
    resources :favourites, only: [:create, :destroy]
    resources :chatrooms do
      resources :messages, only: [:index, :create]
    end

    collection do
      get 'owned'
    end


  end


  resources :bookings, only: :destroy
  resources :reviews, only: :destroy
  resources :guitars, only: :destroy
  resources :chatrooms, only: :index

end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :guitar

  validates :start_date, presence: true
  validates :end_date, presence: true
  validate :booking_dates_cannot_be_in_the_past
  validate :booking_dates_cannot_overlap

  def total_cost
    ((end_date - start_date).to_i + 1) * guitar.cost_per_day
  end

  def booking_dates_cannot_be_in_the_past
    if start_date.present? && start_date < Date.today
      errors.add(:start_date, "can't be in the past")
    end
    if end_date.present? && end_date < Date.today
      errors.add(:end_date, "can't be in the past")
    end
  end

  def booking_dates_cannot_overlap
    if guitar && start_date && end_date
      overlapping_bookings = guitar.bookings.where.not(id: id)
        .where("(start_date <= ? AND end_date >= ?) OR (start_date >= ? AND start_date <= ?)", end_date, start_date, start_date, end_date)
      if overlapping_bookings.any?
        errors.add(:base, "This guitar is already booked for the selected dates")
      end
    end
  end

  def num_days
    num = (end_date - start_date).to_i
    if num == 1
      "£#{guitar.cost_per_day} x #{num} day"
    else
      "£#{guitar.cost_per_day} x #{num} days"
    end
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @user = current_user
    @history = @user.bookings.where("end_date < ?", Date.today)
    @upcoming = @user.bookings.where("end_date > ?", Date.today)
  end

  def create
    @guitar = Guitar.find(params[:guitar_id])
    @booking = @guitar.bookings.build(booking_params)
    @booking.user = current_user
    if @booking.save
      redirect_to user_booking_path(current_user, @booking), notice: "Booking created successfully."
    else
      puts @booking.errors.full_messages
      redirect_to @guitar, notice: "Booking failed."
    end
  end

  def edit
    @booking = Booking.find(params[:id])
    if @booking.update(booking_params)
      redirect_to @booking
    else
      render :edit
    end
  end

  def show
    @user = current_user
    @booking = Booking.find(params[:id])
    @markers =
    [
      lat: @booking.guitar.user.latitude,
      lng: @booking.guitar.user.longitude,
      info_window_html: render_to_string(partial: "guitars/info_window", locals: {booking: @booking}),
      marker_html: render_to_string(partial: "guitars/marker")
    ]
  end

  def update
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to user_bookings_path(current_user)
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :guitar_id)
  end

  def number_of_days
    (booking.end_date - booking.start_date).to_i + 1
  end
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/edit.html.erb
<h1>Bookings#edit</h1>
<p>Find me in app/views/bookings/edit.html.erb</p>

app/views/bookings/index.html.erb
<div class="container mt-3">

  <h2>Upcoming Bookings</h2>
  <hr>

  <% if @upcoming.present?%>

    <% @upcoming.each do |booking| %>
    <div class="upcoming d-flex justify-content-between mb-2">

        <div class="booking-image">
          <%= cl_image_tag booking.guitar.photos.first.key, loading: "lazy" %>
        </div>

      <div class="body">

        <div>
          <h5 class="title"><%= booking.guitar.name %></h5>
          <h6 class="confirmation">#GUI000<%= 1000000 + booking.id %></h6>
        </div>

        <div class="details">
          <p class="text"><%= booking.start_date.strftime("%a-%d-%b") %> to <%= booking.end_date.strftime("%a-%d-%b") %></p>
          <p class="text">£<%= booking.guitar.cost_per_day %> per day</p>
          <p class="text">Total: £<%= booking.total_cost %></p>
        </div>

        <div class="actions">
          <%= link_to "View", user_booking_path(current_user, booking) %>
          <%#= link_to "Edit", edit_user_booking_path(current_user, booking.guitar) %>
          <%#= simple_form_for([current_user, booking], authenticity_token: true, method: :delete) do |f| %>
            <%#= f.button :submit, "Delete", class: "btn btn-danger" %>
          <%# end %>
          <%#= button_to "Message", guitar_chatrooms_path(guitar_id: booking.guitar.id), method: :post, class: "btn btn-dark" %>
</div>
      </div>

    </div>
  <% end %>

  <% else %>

  <div class="no-content">
    <h6>You have no upcoming rentals</h6>
  </div>
  <% end %>
  <br>
  <h2>Booking History</h2>
  <hr>
  <% if @history.present?%>
  <% @history.each do |booking| %>
     <div class="history d-flex justify-content-between mb-2">

        <div class="booking-image">
          <%= cl_image_tag booking.guitar.photos.first.key, loading: "lazy" %>
        </div>

      <div class="body">

        <div>
          <h5 class="title"><%= booking.guitar.name %></h5>
          <h6 class="confirmation">#GUI000<%= 1000000 + booking.id %></h6>
        </div>

        <div class="details">
          <p class="text"><%= booking.start_date.strftime("%a-%d-%b") %> to <%= booking.end_date.strftime("%a-%d-%b") %></p>
          <p class="text">£<%= booking.guitar.cost_per_day %> per day</p>
          <p class="text">Paid: £<%= booking.total_cost %></p>
        </div>

        <div class="actions">
          <%= link_to "Book", guitar_path(booking.guitar) %>
          <a href="#">Review</a>
          <a href="#">Message</a>
          <%#= link_to "Edit", edit_user_booking_path(current_user, booking.guitar) %>
          <%#= link_to "Delete", booking_path(booking.guitar), method: "delete", data: { confirm: 'Are you sure?' } %>
        </div>
      </div>

    </div>
  <% end %>

  <% else %>
  <div class="no-content">
    <h6>You haven't booked anything yet</h6>
    <p><%= link_to "Browse Guitars", guitars_path %></p>
  <% end %>
</div>
</div>

app/views/bookings/show.html.erb
<div class="booking-container">

  <div class="booking-guitar">
    <%= link_to "< All Bookings", user_bookings_path(current_user) %>

    <h3><%= link_to @booking.guitar.name, guitar_path(@booking.guitar) %></h3>

    <%= simple_form_for([current_user, @booking], authenticity_token: true, method: :delete) do |f| %>
      <%= f.button :submit, "Cancel Booking", class: "btn btn-dark" %>
    <% end %>
  </div>

  <div class="booking-details">
    <div class="confirmed">
      <h1><i class="bi bi-check-circle-fill"></i> Booking Confirmed</h1>
    </div>
    <hr>
    <div class="booking-number">
        <h4 class="confirmation">CONFIRMATION: #GUI000<%= 1000000 + @booking.id %></h4>
    </div>
    <hr>
    <div class="collection">
      <div class="d-flex align-items-center">
        <%= image_tag("avatar.jpg") %>
        <h4>Renting from <%= @booking.guitar.user.first_name %></h4>
      </div>
      <p>Pick up guitar from: <%= @booking.guitar.user.address %></p>
      <div class="edit d-flex justify-space-between">
        <p class="text"><%= @booking.start_date.strftime("%a-%d-%b") %> to <%= @booking.end_date.strftime("%a-%d-%b") %></p>
        <a href="#">Edit Booking</a>
      </div>
        <div class = "map container col-sm mb-3" data-controller="map" data-map-markers-value="<%= @markers.to_json %>" data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
    </div>


  </div>

  <div class="payment">
    <h4>Payment Summary</h4>
    <hr>
    <p class="text">RENTAL COST: £<%= @booking.guitar.cost_per_day %> per day</p>
    <p><%= @booking.num_days%></p>
    <p class="text">TOTAL: £<%= @booking.total_cost %></p>
    <button>Pay Now</button>
  </div>

  <div class="conditions">
    <h6>Rental Conditions</h6>
    <ol class="conditions-text">
      <li>The renter must agree to pay the agreed-upon rental fee, which is due at the beginning of the rental period.</li>
      <li>The rental period will begin on the agreed-upon start date and end on the agreed-upon end date. If the renter wishes to extend the rental period, they must contact the owner to make arrangements.</li>
      <li>The guitar must be returned in the same condition it was in at the start of the rental period, except for normal wear and tear.</li>
      <li>The renter is responsible for any damage or loss that occurs to the guitar during the rental period.</li>
      <li>The renter is responsible for any repairs or maintenance required due to damage or loss during the rental period.</li>
      <li>The owner is not responsible for any injury or harm that occurs to the renter or any third parties as a result of the rental or use of the guitar.</li>
      <li>The renter must agree to use the guitar for its intended purpose and not engage in any activities that may damage the guitar or create a risk of harm to themselves or others.</li>
      <li>The renter may not sublease or lend the guitar to any third parties without the owner's prior written consent.</li>
      <li>The owner reserves the right to terminate the rental agreement at any time if the renter violates any of the terms and conditions.</li>
      <li>The renter agrees to indemnify and hold the owner harmless from any and all claims, damages, expenses, or liabilities that arise from the rental or use of the guitar.</li>
</ol>
  </div>













    <div class="body" style="display: none">
    <div class="booking-image">
      <%= cl_image_tag @booking.guitar.photos.first.key, loading: "lazy" %>
    </div>


      <div>
        <h5 class="title"><%= @booking.guitar.name %></h5>
      </div>

      <div class="details">
      </div>
    </div>

  </div>