config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "pages#home"

  resources :users do
    resources :bookings
    resources :reviews
    resources :guitars
    resources :favourites, only: [:index]
  end

  resources :guitars do
    resources :bookings
    resources :reviews
    resources :favourites, only: [:create, :destroy]
    resources :chatrooms do
      resources :messages, only: [:index, :create]
    end

    collection do
      get 'owned'
    end


  end


  resources :bookings, only: :destroy
  resources :reviews, only: :destroy
  resources :guitars, only: :destroy
  resources :chatrooms, only: :index

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="mt-3">
  <div class="container">
    <h2>PICKUPS</h2>
    <p>The best pick for guitar rentals</p>
    <div class="links">
      <i class="bi bi-facebook"></i>
      <i class="bi bi-instagram"></i>
      <i class="bi bi-twitter"></i>
      <i class="bi bi-envelope-at"></i>
    </div>
    <div class="infos">
      <a href="#">Privacy Policy</a>
      <a href="#">Cookie Notice</a>
      <a href="#">Terms of Use</a>
      <a href="#">Advertise</a>
      <a href="#">Contact</a>
    </div>
    <h6>PICKUPS.com | Guitar Rentals Inc.</h6>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <h5>PICKUPS</h5>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>

          <li class="nav-item active">
            <h6><%#= link_to "Guitars", guitars_path, class: "nav-link" %></h6>
          </li>

          <li class="nav-item dropdown">
            <i class="bi bi-list" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>

            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "All Guitars", guitars_path, class: "dropdown-item" %>
              <%= link_to "Inbox", chatrooms_path, class: "dropdown-item" %>
              <%= link_to "Bookings", user_bookings_path(current_user), class: "dropdown-item" %>
              <%= link_to "My Guitars", owned_guitars_path(current_user), class: "dropdown-item" %>
              <%= link_to "Favourites", user_favourites_path(current_user), class: "dropdown-item" %>
              <hr>
              <%= link_to "Account", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>