config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "pages#home"

  resources :users do
    resources :bookings
    resources :reviews
    resources :guitars
    resources :favourites, only: [:index]
  end

  resources :guitars do
    resources :bookings
    resources :reviews
    resources :favourites, only: [:create, :destroy]
    resources :chatrooms do
      resources :messages, only: [:index, :create]
    end

    collection do
      get 'owned'
    end


  end


  resources :bookings, only: :destroy
  resources :reviews, only: :destroy
  resources :guitars, only: :destroy
  resources :chatrooms, only: :index

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_user, only: [:show, :edit, :new, :create, :update, :destroy]

  def new
    @guitar = Guitar.find(params[:guitar_id])
    @review = Review.new
  end

  def create
    @guitar = Guitar.find(params[:guitar_id])
    @review = @guitar.reviews.new(review_params)
    @review.user = current_user
    if @review.save
      redirect_to @guitar, notice: 'Review was successfully created.'
    else
      render :new
    end
  end

  def edit
    @guitar = Guitar.find(params[:guitar_id])
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])
    @review.user = current_user
    if @review.update(review_params)
      redirect_to guitar_path(@review.guitar)
    else
      render :edit
    end
  end

  def destroy
    # @review = Review.find(params[:id])
    # @review.destroy
    # redirect_to guitar_path(@review.guitar)
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end

  def set_review
    @review = Review.find(params[:id])
  end

  def set_user
    @user = current_user
  end
end

app/views/reviews/_review_modal.html.erb
<div class="review-modal">
  <div class="review-container">
    <div class="review-info d-flex justify-content-between">
      <div class="d-flex">
          <p><%= @guitar.average_rating %></p>
          <p id="reviews"><%= @guitar.reviews.count %> reviews</p>
        </div>
      <div class="d-flex">
        <% if @reviewable %>
          <p id="write-review"><%= link_to "Write a review", new_guitar_review_path(@guitar)%></p>
        <% end %>
          <p class="close" data-action="click->modal#closeReview"><i class="bi bi-x-circle"></i></p>
      </div>
    </div>
    <div>

    <% if @guitar.reviews.empty? %>
      <p>No reviews yet</p>
    <% else %>
      <% @guitar.reviews.each do |review| %>

        <div class="review-card">
          <div class="review-avatar"><%= image_tag("avatar.jpg") %></div>
          <div class="review-user">
            <p><%= review.user.first_name %></p>
            <p><%= review.created_at.strftime("%B %Y") %></p>
          </div>
          <div class="review-text">
            <p ><%= review.comment %></p>
          </div>
        </div>

      <% end %>
    <% end %>
    </div>
  </div>
</div>

app/views/reviews/edit.html.erb
<div class="container">
  <h1>Edit Review</h1>
  <%= simple_form_for [@guitar, @review] do |f| %>
    <%= f.input :rating %>
    <%= f.input :comment %>
    <%= f.submit 'Save' %>
</div>

app/views/reviews/new.html.erb
<div class="container mt-5 mb-5">
  <h1>New Review</h1>
  <%= simple_form_for [@guitar, @review] do |f| %>
    <%= f.input :rating %>
    <%= f.input :comment %>
    <%= f.submit 'Save' %>
  <% end %>
</div>